main/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'main'
urlpatterns = [
    path('search/', views.DocumentsResultsView.as_view(), name='searchDocs'),
    path('about-us/',
         TemplateView.as_view(template_name="main/about_us.html")),  # test -- Not OK
    path('', TemplateView.as_view(template_name="main/home.html")),  # test -- OK
    path('index/<int:pk>/', views.DocumentsDetailView.as_view(),
         name='detailsDocs'),  # test --
    path('index/<int:doc_id>/dwn/', views.download,
         name='downloadDocs'),  # test -- (si lien telechargement s'affiche ou pas, si possible de tel...)
    path('index/', views.DocumentsIndexView.as_view(),
         name='indexDocs'),  # test -- OK
    path('rech-avancee-home/',
         TemplateView.as_view(template_name="main/rech_avancee_home.html")),  # test -- Not OK
    path('rech-avancee-index/',
         TemplateView.as_view(template_name="main/docs/rech_avancee_index.html")),  # test -- Not OK
]

memoirepractical/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
import datetime

from django import forms
from django.db import models
from django.utils import timezone


# Create your models here.

# Fields CHOICES: P86
# obj.get_att_display pour avoir les bonnes valeurs

# Nb de jours limites pour qu'un document soit considéré comme vieux
LIMIT_DAYS = 300  # Nombre de jours à ne pas dépasser pour un document passé


class Personne(models.Model):
    nom_complet = models.CharField(max_length=60)

    class Meta:
        ordering = (
            'nom_complet',
        )

    def __str__(self):
        return f"{self.nom_complet}"


class Enseignant(models.Model):
    jur, enc = 'JUR', 'ENC'
    ROLE_CHOICES = [
        (jur, 'Membre du Jury'),
        (enc, 'Encadreur'),
    ]
    ass, cc, mc, pr = 'ASS', 'CC', 'MC', 'PR'
    TITLE_CHOICES = [
        (ass, 'Assistant'),
        (cc, 'Chargé de cours'),
        (mc, 'Maitre de Conférence'),
        (pr, 'Professeur'),
    ]

    enseignant = models.ForeignKey(Personne, on_delete=models.CASCADE)
    titre_enseignant = models.CharField(max_length=3, choices=TITLE_CHOICES)
    role_enseignant = models.CharField(max_length=3, choices=ROLE_CHOICES)

    def __str__(self):
        return f"{self.titre_enseignant} {self.enseignant} ({self.role_enseignant})"


class Etudiant(models.Model):
    etudiant = models.ForeignKey(Personne, on_delete=models.CASCADE)
    matricule = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.etudiant}"


class Document(models.Model):
    # workflow des états du document: en cours, soutenu, archivé
    """ Les fields: P252
    Pour ce modèle, Un document est une these ou un mémoire
    on pourra l'étenre à autre chose plus tard
    """

    # On ordone l'affichage des documents
    class Meta:
        ordering = (
            '-date_soutenance', 'titre_doc'
        )

    fsjp = 'FSJP'
    fseg = 'FSEG'
    ETABLISSEMENT_CHOICES = [
        (fsjp, 'Faculté des Sciences Juridiques et Politiques'),
        (fseg, 'Faculté des Sciences Economiques et de Gestion'),
    ]
    master = 'MAS'
    doctorat = 'DOC'
    TYPE_DIPLOMES = [
        (master, 'Mémoire de Master'),
        (doctorat, 'Thèse de Doctorat'),
    ]
    acca = 'ACC'
    pro = 'PRO'
    TYPE_FORMATION = [
        (acca, 'Formation Académique'),
        (pro, 'Formation professionnelle'),
    ]

    type_doc = models.CharField(
        max_length=3, choices=TYPE_DIPLOMES, default=master, null=True)
    titre_doc = models.CharField(max_length=50, null=False)
    resume_doc = models.TextField(null=True)
    date_selection = models.DateField(
        'Date de Selection', null=True, blank=True)

    pub_date = models.DateTimeField(
        'Date de Publication ', null=True, default=timezone.now)
    est_soutenu = models.BooleanField(default=False)
    date_soutenance = models.DateField(
        'Date de Soutenance', null=True, blank=True)
    note_soutenance = models.DecimalField(
        max_digits=4, decimal_places=2, null=True, blank=True)
    # Pour définir l'heure actuelle on peut utiliser django.utils.timezone.now()

    auteur = models.ForeignKey(Etudiant, on_delete=models.CASCADE)

    etablissement = models.CharField(
        max_length=6, choices=ETABLISSEMENT_CHOICES, default=fseg, null=True)
    type_formation = models.CharField(
        max_length=3, choices=TYPE_FORMATION, default=acca, null=True)
    filiere = models.CharField(max_length=20, null=True)

    jury = models.ManyToManyField(Enseignant, related_name="jury")
    encadreur = models.ManyToManyField(Enseignant, related_name="encadreur")

    # code_doc_pdf= models.CharField(max_length=10) #Le nom du fichier sera son id
    # doc.fichier == None teste si le fichier existe
    fichier = models.FileField(upload_to='uploads/docs', null=True, blank=True)

    def __str__(self):
        return f"{self.type_doc} de {self.auteur}, titre: {self.titre_doc}"

    def est_document_recent(self):
        """
        Renvoie True si le document fut publié récemments
        Ecrire un test pour ça
        pub_date doit être dans la plage de moins de 24h
        """
        now = timezone.now()
        il_ya_nb_j = now - datetime.timedelta(days=LIMIT_DAYS)
        # return il_ya_nb_j <= self.pub_date <= now
        # On se limite à la date actuelle
        return il_ya_nb_j <= self.pub_date <= now


# def recherche_avec_liste_elements(cles):
#     """
#     retourne une liste de résultats pour chaque elements de la liste initiale
#     """
#     liste_retour = []
#     if len(cles) != 0:
#         for q in cles:
#             l = m.Document.objects.filter(
#                 titre_doc__icontains=q).distinct()
#             liste_retour.append(l)
#     return liste_retour


def create_document_test(jours):
    # temps = timezone.now() - datetime.timedelta(20)
    # cette methode marche aussi au niveau du shell
    pers = Personne(nom_complet=f"MTA23 {jours}")
    pers.save()
    etud = Etudiant(etudiant=pers, matricule=f"ZZZ {jours}")
    etud.save()
    ens = Enseignant(enseignant=pers)
    ens.save()

    doc = Document.objects.create(
        titre_doc=f"Debut du mouvement {jours}",
        pub_date=timezone.now() - datetime.timedelta(days=jours),
        auteur=etud,
    )
    doc.save()
    doc.encadreur.add(ens)
    doc.jury.add(ens)
    doc.save()
    return doc

main/views.py
# -*- coding:Utf-8 -*
import datetime

from django.shortcuts import render, get_object_or_404
from django.views import generic  # P287
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponse
from django.db.models import Q

import main.models as m

# Create your views here.

# Afficher la liste des documents publiés récemments


class DocumentsIndexView(generic.ListView):
    paginate_by = 6
    template_name = 'main/docs/index_documents.html'
    context_object_name = 'latest_document_list'

    def get_queryset(self):
        """
        Retourne les documents récents dans un delai d'une semaine
           """
        return m.Document.objects.filter(
            pub_date__lte=timezone.now(),
            pub_date__gt=timezone.now() - datetime.timedelta(m.LIMIT_DAYS),
        ).order_by('-pub_date')  # [:10]

# class DocumentQuerySet() 06:55 dans les modèles


class DocumentsResultsView(generic.ListView):
    paginate_by = 6

    model = m.Document
    template_name = 'main/docs/search_documents.html'
    # A appeler apres la saisie et la validation dans le champ de recherche
    context_object_name = 'document_list'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('q')
        return context

    def get_queryset(self):
        # query = self.request.GET.get('q')
        # retourne la liste dans la requete
        query = self.request.GET.get('q')
        print(query)
        queries = query.strip().split(" ")
        # rechercher sur chaque element de la liste

        document_list = m.Document.objects.filter(
            Q(titre_doc__icontains=query) |
            Q(auteur__etudiant__nom_complet__icontains=query) |
            Q(resume_doc__icontains=query),
            pub_date__lte=timezone.now(),
            pub_date__gt=timezone.now() - datetime.timedelta(m.LIMIT_DAYS),
        )  # Tous les résultats doivent être uniques

        # en cas de plusieurs mots clés
        if len(queries) > 1:
            for cle in queries:
                document_list & (   # Opérateur qui append 2 querysets
                    m.Document.objects.filter(
                        Q(titre_doc__icontains=cle) | Q(
                            type_doc__icontains=cle) | Q(resume_doc__icontains=cle),
                        pub_date__lte=timezone.now(),
                        pub_date__gt=timezone.now() - datetime.timedelta(m.LIMIT_DAYS))
                )

        # list1.append(recherche_avec_liste_elements(cles=queries))

        # le set garantit qu'on aura que des éléments uniques
        # document_list = list(set(list1))

        return document_list.order_by('-pub_date')

# class DocumentsResultsView(generic.ListView):
#     paginate_by = 6

#     model = m.Document
#     template_name = 'main/docs/search_documents.html'
#     # A appeler apres la saisie et la validation dans le champ de recherche

#     def get_queryset(self):
#         list1 = []
#         query = self.request.GET.get('q')  # rechercher sur toute la requete
#         # rechercher sur chaque element de la liste
#         queries = str(query).split(" ")

#         document_list = m.Document.objects.filter(
#             titre_doc__icontains=query)  # Tous les résultats doivent être uniques
#         # Ajout de la seconde recherche dans la liste
#         # list1.append(recherche_avec_liste_elements(cles=queries))

#         # le set garantit qu'on aura que des éléments uniques
#         #document_list = list(set(list1))

#         return document_list


class DocumentsDetailView(generic.DetailView):  # P656
    model = m.Document
    template_name = 'main/docs/details_document.html'

    def get_queryset(self):
        """
        Retourne les 10 documents récents dans un delai d'une semaine
           """
        return m.Document.objects.filter(
            pub_date__lte=timezone.now(),
            pub_date__gt=timezone.now() - datetime.timedelta(m.LIMIT_DAYS),
        )

# vue qui gère le telechargement d'un fichier


def download(request, doc_id):  # Refléchir dessus à tete reposée
    print("docs id ", doc_id)
    doc = get_object_or_404(m.Document, pk=doc_id)
    fic = doc.fichier
    response = HttpResponse(content_type='application/vnd.pdf')
    response['Content-Disposition'] = f'attachment; filename="{fic.name}"'
    return response  # de django.http

main/templates/main/docs/details_document.html
{% extends "../base_list.html" %}


{% block content  %}
<br/>
<div class="table-responsive font-table">
<table class="table">
    <tr class="table-primary">
      <th>{{ document.get_type_doc_display }}</th>
    </tr>
    <tr class="table-default">
      <th>Année de Soutenance:</th>
      <td>{{ document.annee_soutenance }}</td>
    </tr>
    <tr class="table-default">
      <th>Titre : </th>
      <td>{{ document.titre_doc|linebreaks }}</td>
    </tr>
    <tr class="table-default">
      <th>Resumé: </th>
      <td>{{ document.resume_doc }}</td>
    </tr>
    <tr class="table-default">
      <th>Publié le: </th>
      <td>{{ document.pub_date|date:"F Y" }}</td>
    </tr>
    <tr class="table-default">
      <th>Auteur: </th>
      <td>{{ document.auteur }}</td>
    </tr>
    <tr class="table-default">
      <th>Membres du jury: </th>
      <td><ul>
      {% for jur in document.jury.all %}
      <li> {{ jur }} </li>
      {% endfor %}</td></ul>
    </tr>
    <tr class="table-default">
      <th>Encadreur: </th>
      <td><ul>
      {% for enc in document.encadreur.all %}
      <li> {{ enc }} </li>
      {% endfor %}</td></ul>
    </tr>
    <tr class="table-default">
     {% if document.fichier %}
      <th> </th>
      <td> <a href="{% url 'main:downloadDocs' document.id %}">Telecharger le pdf</a></td>   
     {% endif %}
    </tr>  
  </table>
</div>
{% endblock content  %}
  
  

main/templates/main/docs/index_documents.html
{% extends "../static_base_list.html" %}

  {% block content2  %}
    <div class="result-blocks">

      {% if latest_document_list %}

        {% for document in page_obj %}
          <div class="doc-block">
            <p class="titre-block card-title"> {{ document.get_type_doc_display }} </p>
            <p class="card-text">
              <span class="titre-doc" > {{ document.titre_doc }}</span> &middot; par
              <span class="auteur-doc"> {{ document.auteur }} </span>
            </p>
            <p class="resume"> 
              {{ document.resume_doc }}
              Following a re-engineering approach, this chapter presents an initial 
              framework for ERM method construction. The framework is defined using 
              actual proposals from the literature, by transforming existing approaches 
              to their modular version. 
            </p>
            <p class="doc-block_footer">{{ document.pub_date|date:"F Y" }} 
              <a href="{% url 'main:detailsDocs'  pk=document.id %}" class="btn btn-outline-info">
                détails...</a> </p>
          </div> <br/>
        {% endfor %}

      {% else %}
        <div>
          <p>Aucun Document n'est disponible.</p>
        </div>

      {% endif %}

{% if is_paginated %}
<nav id="navbar">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href = "{% url 'main:indexDocs' %}?page={{ page_obj.previous_page_number }}" >
                    Previous
                </a>
            </li> 
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Previous</a>
            </li>
        {% endif %}
        {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %}
            active{% endif %}">
            <a class="page-link" href="?page={{pagenum}}">{{pagenum}}</a>
        </li>
        {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
      {% endif %}
    </ul>
</nav>
{% endif %}
</div>
   

{% endblock content2  %}

main/templates/main/docs/rech_avancee_index.html
{% extends "./base_list.html" %} {% block content %}
<div>
  <form
    class="bloc-form-results"
    method="GET"
    action="{% url 'main:searchDocs' %}"
  >
    <input
      name="q"
      id="id_q"
      class="form-control2 mr-sm-2"
      type="text"
      placeholder="Saisir un titre, auteur, mot clé ici..."
    />
    <button
      class="bouton-search btn btn-outline-success my-2 my-sm-0"
      type="submit"
    >
      OK!
    </button>
  </form>
</div>

<!--
<a href="#" class="rech_avancee">Recherche Avancée</a>
-->

<br />

main/templates/main/docs/search_documents.html
{% extends "../static_base_list.html" %}

{% block content2  %}

<div class="result-blocks">
{% if document_list %}

{% for document in page_obj %}

<div class="doc-block">
            <p class="titre-block card-title"> {{ document.get_type_doc_display }} </p>
            <p class="card-text">
              <span class="titre-doc" > {{ document.titre_doc }}</span> &middot; par
              <span class="auteur-doc"> {{ document.auteur }} </span>
            </p>
            <p class="resume"> 
              {{ document.resume_doc }}
              Following a re-engineering approach, this chapter presents an initial 
              framework for ERM method construction. The framework is defined using 
              actual proposals from the literature, by transforming existing approaches 
              to their modular version. 
            </p>
            <p class="doc-block_footer">{{ document.pub_date|date:"F Y" }} 
              <a href="{% url 'main:detailsDocs'  pk=document.id %}" class="btn btn-outline-info">
                détails...</a> </p>
          </div> <br/>

{% endfor %}
{% else %}
<div>
    <p>Aucun Document n'est disponible.</p>
</div>
{% endif %}



{% if is_paginated %}
<nav>
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href = "{% url 'main:searchDocs' %}?page={{ page_obj.previous_page_number }}&q={{query}}" >
                    Previous
                </a>
            </li> 
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">Previous</a>
            </li>
        {% endif %}
        {% for pagenum in page_obj.paginator.page_range %}
        <li class="page-item{% if page_obj.number == pagenum %}
            active{% endif %}">
            <a class="page-link" href="{% url 'main:searchDocs' %}?page={{pagenum}}&q={{query}}">{{pagenum}}</a>
        </li>
        {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="{% url 'main:searchDocs' %}?page={{page_obj.next_page_number}}&q={{query}}">Next</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#">Next</a>
        </li>
      {% endif %}
    </ul>
</nav>
</div>


{% endif %}
{% endblock content2  %}